#!/bin/bash

# --- CONFIGURAÇÃO ---
CURRENT_WALLPAPER=$(swww query | grep "image" | awk '{print $NF}' | tr -d '"')
WAL_CACHE="$HOME/.cache/wal/colors.json"

# Arquivos de saída
HYPRLAND_CONFIG="$HOME/.config/hypr/hyprland_pywal.conf"
WAYBAR_THEME_FILE="$HOME/.config/waybar/colors.css"
HYPRLOCK_CONFIG="$HOME/.config/hypr/hyprlock_pywal.conf" 
SPICETIFY_CONFIG="$HOME/.config/spicetify/Themes/pywal-theme/color.ini" 

# --- FUNÇÕES ---

generate_spicetify_config() {
    echo "Generating Spicetify color.ini..."
    if [ ! -f "$WAL_CACHE" ]; then echo "🚨 ERROR: Pywal cache not found."; return; fi
    
    local BG_COLOR=$(jq -r '.colors.color0' "$WAL_CACHE")
    local FG_COLOR=$(jq -r '.colors.color15' "$WAL_CACHE")
    local ACCENT_COLOR=$(jq -r '.colors.color4' "$WAL_CACHE") 
    
    mkdir -p "$(dirname "$SPICETIFY_CONFIG")"
    
    cat > "$SPICETIFY_CONFIG" << EOF
[Base]
text              = $FG_COLOR
subtext           = $(jq -r '.colors.color7' "$WAL_CACHE")
sidebar           = $BG_COLOR
main_bg           = $BG_COLOR
main_fg           = $FG_COLOR
main_accent       = $ACCENT_COLOR
cover_overlay     = $(jq -r '.colors.color8' "$WAL_CACHE")
shadow            = #000000
EOF

    if command -v spicetify &> /dev/null; then
        spicetify config current_theme pywal-theme
        # Usa --no-restart para evitar que o Spotify abra
        spicetify apply --no-restart 
        echo "Spicetify applied (no restart)."
    else
        echo "⚠️ WARNING: Spicetify command not found."
    fi
}

# --- EXECUÇÃO PRINCIPAL ---

if [ -z "$CURRENT_WALLPAPER" ]; then exit 1; fi
echo "Applying colors from: $CURRENT_WALLPAPER"
wal -n -i "$CURRENT_WALLPAPER"

# --- 1. Hyprland: env = key, RRGGBB & BORDER COLORS (FIXED SYNTAX) ---
echo "Generating Hyprland variables and border commands..."
{
    # Variáveis de ambiente (env = key, RRGGBB)
    jq -r '.colors | to_entries[] | "env = \( .key ), \( .value | sub("^#"; "") )"' "$WAL_CACHE"
    
    # Cores de borda com prefixo 0xFF (ARGB) para garantir a sintaxe correta do Hyprland
    ACCENT_HEX=$(jq -r '.colors.color4 | sub("^#"; "")' "$WAL_CACHE")
    INACTIVE_HEX=$(jq -r '.colors.color8 | sub("^#"; "")' "$WAL_CACHE")
    
    # exec-once para bordas do lado do servidor (terminais)
    echo "exec-once = hyprctl setprop general:col.active_border 0xFF${ACCENT_HEX}"
    echo "exec-once = hyprctl setprop general:col.inactive_border 0xFF${INACTIVE_HEX}"

} > "$HYPRLAND_CONFIG"

# --- 2. Waybar: @define-color key #RRGGBB ---
echo "Generating Waybar CSS variables..."
echo "/* Automatically generated by Pywal/jq */" > "$WAYBAR_THEME_FILE"
jq -r '.colors | to_entries[] | "@define-color \( .key ) \( .value );"' "$WAL_CACHE" >> "$WAYBAR_THEME_FILE"

# --- 3. Hyprlock: $key = 0xffRRGGBB ---
echo "Generating Hyprlock color variables..."
jq -r '.colors | to_entries[] | "$\(.key) = 0xff\( .value | sub("^#"; "") )"' "$WAL_CACHE" > "$HYPRLOCK_CONFIG"

# 4. Spicetify
generate_spicetify_config

# 5. Recarregamento
echo "Reloading Hyprland and Waybar..."
hyprctl reload & 
killall -q waybar
sleep 0.2
nohup waybar &>/dev/null &

echo "✅ Color application complete."