#!/bin/bash

# --- MAIN CONFIG --- #
CURRENT_WALLPAPER=$(swww query | grep "image" | awk '{print $NF}' | tr -d '"')
WAL_CACHE="$HOME/.cache/wal/colors.json"

# --- OUTPUT FILES --- #
HYPRLAND_CONFIG="$HOME/.config/hypr/hyprland_pywal.conf"
WAYBAR_THEME_FILE="$HOME/.config/waybar/colors.css"
HYPRLOCK_CONFIG="$HOME/.config/hypr/hyprlock_pywal.conf" 
WLOGOUT_CONFIG="$HOME/.config/wlogout/colors.css"
ROFI_CONFIG="$HOME/.config/rofi/colors.rasi"
SWAYNC_CONFIG="$HOME/.config/swaync/colors.css"
SPICETIFY_CONFIG="$HOME/.config/spicetify/Themes/tui/color.ini"

# --- FUNCTIONS --- #

generate_spicetify_config() {
    if [ ! -f "$WAL_CACHE" ]; then echo "🚨 ERROR: Pywal cache not found."; return; fi
    
    local CO0=$(jq -r '.colors.color0' "$WAL_CACHE" | sed 's/#//')
    local CO1=$(jq -r '.colors.color1' "$WAL_CACHE" | sed 's/#//')
    local CO2=$(jq -r '.colors.color2' "$WAL_CACHE" | sed 's/#//')
    local CO3=$(jq -r '.colors.color3' "$WAL_CACHE" | sed 's/#//')
    local CO4=$(jq -r '.colors.color4' "$WAL_CACHE" | sed 's/#//')
    local CO5=$(jq -r '.colors.color5' "$WAL_CACHE" | sed 's/#//')
    local CO6=$(jq -r '.colors.color6' "$WAL_CACHE" | sed 's/#//')
    local CO7=$(jq -r '.colors.color7' "$WAL_CACHE" | sed 's/#//')
    local CO8=$(jq -r '.colors.color8' "$WAL_CACHE" | sed 's/#//')
    local CO9=$(jq -r '.colors.color9' "$WAL_CACHE" | sed 's/#//')
    local CO10=$(jq -r '.colors.color10' "$WAL_CACHE" | sed 's/#//')
    local CO11=$(jq -r '.colors.color11' "$WAL_CACHE" | sed 's/#//')
    local CO12=$(jq -r '.colors.color12' "$WAL_CACHE" | sed 's/#//')
    local CO13=$(jq -r '.colors.color13' "$WAL_CACHE" | sed 's/#//')
    local CO14=$(jq -r '.colors.color14' "$WAL_CACHE" | sed 's/#//')
    local CO15=$(jq -r '.colors.color15' "$WAL_CACHE" | sed 's/#//')

    mkdir -p "$(dirname "$SPICETIFY_CONFIG")"

    cat > "$SPICETIFY_CONFIG" << EOF
[Pywal Theme]
accent             = $CO10
accent-active      = $CO10
accent-inactive    = $CO10
banner             = $CO10
border-active      = $CO10
border-inactive    = $CO8
header             = $CO10
highlight          = $CO10
main               = $CO0
notification       = $CO15
notification-error = $CO15
subtext            = $CO15
text               = $CO15
EOF
}

generate_rofi_config() {
    if [ ! -f "$WAL_CACHE" ]; then echo "🚨 ERROR: Pywal cache not found."; return; fi

    # Extract colors with jq
    local $CO0=$(jq -r '.colors.color0' "$WAL_CACHE")
    local BG=$(jq -r '.colors.color0' "$WAL_CACHE")
    local FG=$(jq -r '.colors.color15' "$WAL_CACHE")
    local ACCENT_COLOR=$(jq -r '.colors.color6' "$WAL_CACHE")
    local BG_ALT=$(jq -r '.colors.color10' "$WAL_CACHE")
    local SELECT=$(jq -r '.colors.color10' "$WAL_CACHE")
    local ACCENT_TRANS="${ACCENT_COLOR}CC"

    mkdir -p "$(dirname "$ROFI_CONFIG")"

    # Fix: Use $ROFI_CONFIG variable and add semicolons for Rasi syntax
    cat > "$ROFI_CONFIG" << EOF
* {
    bg: ${BG}B3;        /* Increased transparency (70%) */
    bg-alt: ${BG_ALT}E6;
    fg: ${FG};
    accent-trans: ${ACCENT_TRANS};
    accent: ${ACCENT_COLOR};
    urgent: ${SELECT};
    select: ${SELECT};
    back-image: url("${CURRENT_WALLPAPER}", height);
}
EOF
}

# --- EXECUTION --- #

if [ -z "$CURRENT_WALLPAPER" ]; then exit 1; fi
echo "Applying colors from: $CURRENT_WALLPAPER"
wal -n -i "$CURRENT_WALLPAPER"

echo "Generating Hyprland variables and border commands..."
{
    jq -r '.colors | to_entries[] | "env = \( .key ), \( .value | sub("^#"; "") )"' "$WAL_CACHE"
    
    ACCENT_HEX=$(jq -r '.colors.color4 | sub("^#"; "")' "$WAL_CACHE")
    INACTIVE_HEX=$(jq -r '.colors.color8 | sub("^#"; "")' "$WAL_CACHE")
    
    echo "exec-once = hyprctl setprop general:col.active_border 0xFF${ACCENT_HEX}"
    echo "exec-once = hyprctl setprop general:col.inactive_border 0xFF${INACTIVE_HEX}"

} > "$HYPRLAND_CONFIG"

echo "Generating Waybar CSS variables..."
echo "/* Automatically generated by Pywal/jq */" > "$WAYBAR_THEME_FILE"
jq -r '.colors | to_entries[] | "@define-color \( .key ) \( .value );"' "$WAL_CACHE" >> "$WAYBAR_THEME_FILE"

echo "Generating Hyprlock color variables..."
jq -r '.colors | to_entries[] | "$\(.key) = 0xff\( .value | sub("^#"; "") )"' "$WAL_CACHE" > "$HYPRLOCK_CONFIG"

echo "Generating Wlogout CSS variables..."
echo "/* Automatically generated by Pywal */" > "$WLOGOUT_CONFIG"
jq -r '.colors | to_entries[] | "@define-color \( .key ) \( .value );"' "$WAL_CACHE" >> "$WLOGOUT_CONFIG"

echo "Generating Swaync CSS variables..."
echo "/* Automatically generated by Pywall */" > "$SWAYNC_CONFIG"
jq -r '.colors | to_entries[] | "@define-color \( .key ) \( .value );"' "$WAL_CACHE" >> "$SWAYNC_CONFIG"

generate_rofi_config

generate_spicetify_config

# --- RELOAD TO APPLY COLORS --- #
echo "Reloading Hyprland and Waybar..."
hyprctl reload & 
killall -q waybar

spicetify apply -n

# 2. Se o Spotify já estiver aberto, damos o refresh visual
if pgrep -x "spotify" > /dev/null; then
    spicetify watch -s & sleep 1 && pkill -f "spicetify watch"
    echo "✅ Spotify atualizado ao vivo!"
else
    echo "✅ Cores salvas. O Spotify abrirá com o novo tema na próxima vez."
fi

nohup waybar &>/dev/null &
swaync-client --reload-css
echo "✅ Color application complete."